In [1]:
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
print(np.random.randint.__doc__)


        randint(low, high=None, size=None, dtype=int)

        Return random integers from `low` (inclusive) to `high` (exclusive).

        Return random integers from the "discrete uniform" distribution of
        the specified dtype in the "half-open" interval [`low`, `high`). If
        `high` is None (the default), then results are from [0, `low`).

        .. note::
            New code should use the ``integers`` method of a ``default_rng()``
            instance instead; please see the :ref:`random-quick-start`.

        Parameters
        ----------
        low : int or array-like of ints
            Lowest (signed) integers to be drawn from the distribution (unless
            ``high=None``, in which case this parameter is one above the
            *highest* such integer).
        high : int or array-like of ints, optional
            If provided, one above the largest (signed) integer to be drawn
            from the distribution (see above for behavior if ``high=None``).
 

In [7]:
np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)

array([[ 6,  8,  7,  8],
       [16, 12, 11, 16]], dtype=uint8)

In [21]:
d1 = np.array([x  for x in np.random.randint([20,2000], [168, 16800] ,size = (100, 2))])

In [22]:
d1

array([[   99, 10447],
       [  165,  7447],
       [  102,  4591],
       [  163, 13301],
       [   88, 12288],
       [  139, 15993],
       [   95, 12918],
       [   95, 11885],
       [   49,  6112],
       [   61, 14495],
       [   46,  3474],
       [   87, 16504],
       [   63,  7196],
       [  112,  9776],
       [   97, 12557],
       [   54,  4972],
       [  138, 10167],
       [   82, 13761],
       [  103, 14937],
       [  107, 10680],
       [  106, 16173],
       [   96,  9107],
       [   78,  4823],
       [  129, 15449],
       [  100, 11071],
       [  129,  7282],
       [   80, 12528],
       [  145, 15026],
       [  134,  5009],
       [  126,  5715],
       [   22, 16751],
       [  111, 13685],
       [   61, 11950],
       [   85,  6986],
       [   92,  5642],
       [   55, 13945],
       [  160,  8783],
       [   48,  2313],
       [   38,  6422],
       [   32,  2607],
       [  160,  9196],
       [  132, 12198],
       [   89,  6620],
       [   

In [19]:
import sklearn.datasets as  sd 

In [17]:
print(sc.__doc__)

Calibration of predicted probabilities.


In [20]:
print(sd.__doc__)


The :mod:`sklearn.datasets` module includes utilities to load datasets,
including methods to load and fetch popular reference datasets. It also
features some artificial data generators.



In [8]:
import numpy as np
a = np.array([(a, int((input('Введите ченить')))) for a in range(10)])
a

array([[ 0, 11],
       [ 1,  1],
       [ 2,  1],
       [ 3, 14],
       [ 4, 14],
       [ 5, 14],
       [ 6, 14],
       [ 7, 14],
       [ 8, 14],
       [ 9, 14]])

In [10]:
import numpy as np
a1 = int(input('Введите колличевство ожидаемых значений'))
a = np.array([(a, (input('Введите ченить'))) for a in range(a1)]) # строковой ввод
a

array([['0', '1'],
       ['1', '2'],
       ['2', '3']], dtype='<U11')

In [11]:
import numpy as np

vod = int(input('Введите 0 если хотите ввести int, иначе введите 0 для str'))
if vod == 0:
    a1 = int(input('Введите колличевство ожидаемых значений'))
    a = np.array([(a, int((input('Введите ченить')))) for a in range(10)])
    print(a)
elif vod == 1:
    a2 = int(input('Введите колличевство ожидаемых значений'))
    a = np.array([(a, (input('Введите ченить'))) for a in range(a2)])
    print(a)
    
    

[[0 1]
 [1 2]
 [2 3]
 [3 4]
 [4 4]
 [5 1]
 [6 2]
 [7 2]
 [8 2]
 [9 2]]
